### ISSUE TITLE
Local Rerouting Question

### ISSUE THREAD

**Issue by vinays6** [rtealwitter/OpenStreets#2]
From the paper:
> As described above, we use a simplistic model for inferring routes that ignores traffic. Fortunately, there is an elegant model for inferring routes that takes traffic into account (Christiano et al. 2011). Unfortunately, it only works for undirected graphs.

From what I understand, this would allow global rerouting instead of local rerouting for drivers by using the maximum s-t solution proposed in the paper. Is there a reason why this algorithm was selected over other solutions to the maximum flow problem? (such as [this one](https://arxiv.org/pdf/2203.00671.pdf), which is faster and works for directed graphs)

**Comment by rtealwitter** [comment]
Thanks for your question!

The problem we are interested in is which paths drivers use to go from point $s$ to point $t$. For the paper, we computed the shortest path between $s$ and $t$ then assumed all drivers used it. Of course, this isn't realistic because after 100 drivers have used the shortest path, that path may now be slower than another path and new drivers may switch paths. The reason we use this approach is because we can compute the shortest $s$- $t$ paths efficiently: we just do a Dijkstra exploration from each node in the graph and save the resulting trees. After this $O(n^2)$ preprocessing step we can look up any particular $s$- $t$ path in constant time.

The paper you link to solves the maximum $s$- $t$ flow problem. Note that the solution to this problem may be subtly different than the one we are interested in. In the maximum flow problem, we want to route as much flow from $s$ to $t$ while respecting edge capacities; the path that some flow takes may be much longer than some other flow. This is not the way we think drivers behave: in particular, a driver will always make a greedy decision to take the shortest path at the time that they're driving.

In addition, their algorithm is still too slow. They solve the maximum $s$- $t$ flow problem in (approximately?) linear time. Since there are $O(n^2)$ $s$- $t$ pairs, the total time complexity is roughly $O(n^3)$. In our setting, $n=19391$ so we have something on the order of $7.2 \times 10^{12}$ operations if we run in cubic time instead of $3.8 \times 10^8$ operations if we run in quadratic time.

**Comment by vinays6** [comment]
Thanks for the detailed answer. I'm still kind of confused on why you mention the paper "Christiano et. al 2011", from what I can see it only solves the maximum s-t flow problem and wouldn't be relevant here like you said.
